apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: contabo-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ContaboCluster
    name: contabo-cluster
    namespace: default
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: contabo-cluster-control-plane
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ContaboCluster
metadata:
  name: contabo-cluster
  namespace: default
spec:
  region: "EU"
  network:
    subnets:
    - name: "default"
      cidr: "10.0.0.0/16"
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: contabo-cluster-control-plane
  namespace: default
spec:
  replicas: 3
  machineTemplate:
    infrastructureRef:
      kind: ContaboMachine
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: contabo-cluster-control-plane
      namespace: default
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        criSocket: unix:///var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        criSocket: unix:///var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
  version: "v1.28.0"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ContaboMachine
metadata:
  name: contabo-cluster-control-plane
  namespace: default
spec:
  instanceType: "L"
  image: "ubuntu-22.04"
  region: "EU"
  sshKeys:
    - "my-ssh-key"
  additionalMetadata:
    cluster-name: "contabo-cluster"
    node-role: "control-plane"
  additionalTags:
    cluster.x-k8s.io/cluster-name: "contabo-cluster"
    cluster.x-k8s.io/role: "control-plane"
  network:
    subnetName: "default"
    publicIP: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: contabo-cluster-workers
  namespace: default
spec:
  clusterName: contabo-cluster
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: contabo-cluster
      cluster.x-k8s.io/deployment-name: contabo-cluster-workers
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: contabo-cluster
        cluster.x-k8s.io/deployment-name: contabo-cluster-workers
    spec:
      clusterName: contabo-cluster
      version: "v1.28.0"
      bootstrap:
        configRef:
          name: contabo-cluster-workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          namespace: default
      infrastructureRef:
        name: contabo-cluster-workers
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ContaboMachineTemplate
        namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ContaboMachineTemplate
metadata:
  name: contabo-cluster-workers
  namespace: default
spec:
  template:
    spec:
      instanceType: "M"
      image: "ubuntu-22.04"
      region: "EU"
      sshKeys:
        - "my-ssh-key"
      additionalMetadata:
        cluster-name: "contabo-cluster"
        node-role: "worker"
      additionalTags:
        cluster.x-k8s.io/cluster-name: "contabo-cluster"
        cluster.x-k8s.io/role: "worker"
      network:
        subnetName: "default"
        publicIP: true
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: contabo-cluster-workers
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: unix:///var/run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external