## Append samples of your project ##
resources:
- infrastructure_v1beta1_contabocluster.yaml
- infrastructure_v1beta1_contabomachine.yaml
- infrastructure_v1beta1_contabomachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
